name: FOSSA
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    branches: [master,main,dev-vgpu-1219]
  pull_request:
    branches: [master,main]
  pull_request_target:
    branches: [main,dev-vgpu-1219]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.19.x"

      - name: Checkout submodule
        uses: Mushus/checkout-submodule@v1.0.1
        with:
            submodulePath: libvgpu 

      - run: go version
      # Runs a set of commands to initialize and analyze with FOSSA
      
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_TOKEN }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - run: make vgpu
      - run: TAG_VERSION="${BRANCH_NAME}" make push-vgpu-tag
